# Generated by Django 4.1.7 on 2023-03-03 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Children',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_num', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['level_num'],
            },
        ),
        migrations.CreateModel(
            name='Receptive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anees.level')),
            ],
            options={
                'verbose_name_plural': 'Receptive Games',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='level/social')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anees.level')),
            ],
            options={
                'verbose_name_plural': 'Social Games',
            },
        ),
        migrations.CreateModel(
            name='ReceptiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='level/receptive')),
                ('name', models.CharField(max_length=255)),
                ('receptive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='anees.receptive')),
            ],
            options={
                'verbose_name_plural': 'Receptive Games Images',
            },
        ),
        migrations.CreateModel(
            name='Expressive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='level/expressive')),
                ('answer', models.CharField(max_length=255)),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anees.level')),
            ],
            options={
                'verbose_name_plural': 'Expressive Games',
            },
        ),
        migrations.CreateModel(
            name='conversionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='anees.social')),
            ],
            options={
                'verbose_name_plural': 'Social Games Messages',
            },
        ),
        migrations.CreateModel(
            name='ChildLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptive_complete', models.BooleanField(default=False)),
                ('expressive_complete', models.BooleanField(default=False)),
                ('social_complete', models.BooleanField(default=False)),
                ('receptive_score', models.SmallIntegerField(default=0)),
                ('expressive_score', models.SmallIntegerField(default=0)),
                ('social_score', models.SmallIntegerField(default=0)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='anees.child')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='anees.level')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.AddConstraint(
            model_name='childlevel',
            constraint=models.UniqueConstraint(fields=('level', 'child'), name='level_child_key'),
        ),
    ]
