# Generated by Django 4.1.7 on 2023-03-06 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childlevel',
            options={'ordering': ['level'], 'verbose_name_plural': 'Children Progress'},
        ),
        migrations.AddField(
            model_name='child',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
